lib/ex_typeracer_web/router.ex
defmodule ExTyperacerWeb.Router do
  use ExTyperacerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :auth do
    plug ExTyperacer.Auth.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ExTyperacerWeb do
    pipe_through [:browser, :auth] # Use the default browser stack

    get "/", PageController, :index
    get "/racer/:name_rom", PageController, :racer
    get "/racer", PageController, :racer
    post "/", PageController, :login
    post "/logout", PageController, :logout
    post "/new_user", PageController, :new_user
    get "/recovery/:token/:username", PageController, :recovery
    post "/restore_pass", PageController, :restore_pass
  end

  scope "/ranking", ExTyperacerWeb do
    pipe_through [:browser, :auth] # Use the default browser stack

    get "/", RankingController, :index
  end


  scope "/auth", ExTyperacerWeb do
    pipe_through [:browser, :auth] # Use the default browser stack

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  scope "/auth", ExTyperacerWeb do
    pipe_through [:browser, :auth] # Use the default browser stack

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  scope "/login", ExTyperacerWeb do
    pipe_through [:browser, :auth] # Use the default browser stack
    get "/", LoginController, :index
    post "/", LoginController, :login
    post "/logout", LoginController, :logout
  end

  # Other scopes may use custom stacks.
  # scope "/api", ExTyperacerWeb do
  #   pipe_through :api
  # end
end

lib/ex_typeracer_web/views/layout_view.ex
defmodule ExTyperacerWeb.LayoutView do
  use ExTyperacerWeb, :view
end

lib/ex_typeracer_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>. : Keyboard Heroes : .</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%=link("Keyboard Heroes", to: "/", method: "get", class: "navbar-brand")%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav mr-auto">
          <!--li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
          </li-->
        </ul>
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item">
            <%= link(" ", to: login_path(@conn, :logout), method: :post, class: "fa fa-user-times") %>
          </li>
        </ul>
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item">
            <%=link("Global ranking", to: "/ranking", method: "get", class: "nav-link")%>
          </li>
        </ul>
      </div>
    </nav>


    <%= render @view_module, @view_template, assigns %>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/ex_typeracer_web/templates/layout/login.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>. : Keyboard Heroes : .</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/login.css") %>">
  </head>
  <body style="background-image: url('http://www.techcredo.com/wp-content/uploads/2012/11/retro-8-bit-pixelart-wallpapers-19.jpg')">

    <%= render @view_module, @view_template, assigns %>

  </body>
</html>